# -*- coding: utf-8 -*-
"""Sistema de ponto da Floema.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qT217_FgLneB8_oY5nnfz6THvgjKP3eb
"""

import streamlit as st
import pandas as pd
from datetime import datetime
from zoneinfo import ZoneInfo
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# CONFIGURAÇÃO DA API
escopo = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]
credenciais = ServiceAccountCredentials.from_json_keyfile_name("/content/sistemadeponto-f2ef52fe4ce4.json", escopo)
cliente = gspread.authorize(credenciais)

# Nome da planilha no Google Sheets
planilha = cliente.open("Registro_Ponto")
aba = planilha.worksheet("Dados")  # ou sheet1

# Dados dos colaboradores
colaboradores = {
    "Fernando": 33,
    "Gustavo": 44,
    "Clara": 45,
    "Eveline": 56,
    "Valmir": 37
}

# Criar DataFrame
Dados = pd.DataFrame(list(colaboradores.items()), columns=["Nome", "Codigo"])
colunas_ponto = [
    "Data", "Entrada", "Horário de saída", "Horário de volta do almoço",
    "Horário de saída não programada", "Horário de volta da saída não programada", "Saída"
]
for coluna in colunas_ponto:
    if coluna not in Dados.columns:
        Dados[coluna] = ""

# Gerenciar estado de sessão
if "registrado" not in st.session_state:
    st.session_state.registrado = False

st.set_page_config(page_title="Registro de Ponto", page_icon="🕒")
st.title("🕒 Sistema de Registro de Ponto")

if not st.session_state.registrado:
    codigo = st.number_input("Insira seu código de colaborador:", step=1, format="%d")
    Lista_de_codigos = Dados["Codigo"].values

    if codigo in Lista_de_codigos:
        nome = Dados.loc[Dados["Codigo"] == codigo, "Nome"].values[0]
        st.success(f"Bem-vindo, {nome}!")

        confirma = st.radio("Confirma seu nome?", ["Sim", "Não"])

        if confirma == "Sim":
            opcao = st.selectbox("Escolha uma opção:", [
                "1 - Entrada",
                "2 - Saída para o almoço",
                "3 - Volta para o almoço",
                "4 - Saída não programada",
                "5 - Volta da saída não programada",
                "6 - Saída"
            ])

            if st.button("Registrar"):
                agora = datetime.now(ZoneInfo("America/Sao_Paulo"))
                data = agora.date().strftime("%d/%m/%Y")
                hora = agora.time().strftime("%H:%M:%S")

                campos = {
                    "1": "Entrada",
                    "2": "Horário de saída",
                    "3": "Horário de volta do almoço",
                    "4": "Horário de saída não programada",
                    "5": "Horário de volta da saída não programada",
                    "6": "Saída"
                }

                campo_selecionado = campos[opcao.split(" ")[0]]

                # Enviar os dados para o Google Sheets (linha nova)
                linha = [nome, codigo, data]
                for col in colunas_ponto:
                    if col == campo_selecionado:
                        linha.append(hora)
                    else:
                        linha.append("")

                aba.append_row(linha, value_input_option="USER_ENTERED")
                st.success(f"{campo_selecionado} registrada com sucesso às {hora}!")
                st.session_state.registrado = True
        else:
            st.warning("Por favor, contate o PCP para corrigir o código.")
    else:
        if codigo != 0:
            st.error("Código não encontrado. Tente novamente.")
else:
    if st.button("Registrar outro colaborador"):
        st.session_state.registrado = False